{
  "openapi": "3.0.0",
  "info": {
    "title": "PAYMETRUST API",
    "version": "1.0.0",
    "description": "API For Payment & Transfer with PAYMETRUST API"
  },
  "servers": [
    {
      "url": "https://api.sandbox.paymetrust.net/v1",
      "description": "Sandbox environment"
    },
    {
      "url": "https://api.paymetrust.net/v1",
      "description": "Production environment"
    }
  ],
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "paths": {
    "/oauth/login": {
      "post": {
        "summary": "User Authentication",
        "description": "Authenticates a user using API credentials.",
        "tags": [
          "Authentication"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "api_key": {
                    "type": "string"
                  },
                  "api_password": {
                    "type": "string"
                  }
                },
                "required": [
                  "api_key",
                  "api_password"
                ]
              },
              "example": {
                "api_key": "*********",
                "api_password": "*************"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "status": {
                      "type": "string"
                    },
                    "access_token": {
                      "type": "string"
                    },
                    "token_type": {
                      "type": "string"
                    },
                    "expires_in": {
                      "type": "integer"
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "status": "OK",
                  "access_token": "******",
                  "token_type": "bearer",
                  "expires_in": 86400
                }
              }
            }
          },
          "401": {
            "description": "Failure - Invalid credentials",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "status": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "code": 1005,
                    "status": "INVALID_CREDENTIALS",
                    "description": "The requested service needs credentials, but the ones provided were invalid."
                  }
                }
              }
            }
          }
        }
      }
    },
    "/payment": {
      "post": {
        "summary": "Process Payment",
        "description": "Initiates a payment request. This endpoint supports multiple configurations based on country requirements. Use `XOF` as the currency for West African countries, `XAF` for CEMAC Countries, and specify other fields based on the payment method and country.\n- For **Benin (BJ)**: Use `MOOV_BJ` or  `MTN_BJ`.\n- For **Burkina Faso (BF)**: Use OM_BF,MOOV_BFor WAVE_BF for payment_method.\n- For **CÃ´te d'Ivoire (CI)**: Use `OM_CI`, `MOOV_CI`, `WAVE_CI` or `MTN_CI for payment_method.\n- For **Mali (ML)**: Use `OM_ML`or `MOOV_ML`.\n- For **Cameroon (CM)**: Use `OM_CM` or. `MTN_CM`.\n- For **Guninea (GN)**: Use `OM_GN`or `MTN_GN`.\n- For **Senegal (SN)**: Use `OM_SN`, `WAVE_SN`,`FREE_SN`or `EXPRESSO_SN`.\n- For **Togo (TG)**: Use `MOOV_TG` or `TMONEY_TG`.\n- For **Niger (NE)**: Use `AIRTEL_NE`.\n- For **RDC (CD)**: Use `OM_CD`, `AIRTEL_CD`,`MPESA_CD`or `AFRICELL_CD`.\n",
        "tags": [
          "Payment"
        ],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "oneOf": [
                  {
                    "type": "object",
                    "required": [
                      "currency",
                      "merchant_transaction_id",
                      "amount",
                      "client_phone_number",
                      "payment_method",
                      "otp_code",
                      "success_url",
                      "failed_url",
                      "notify_url",
                      "designation",
                      "client_first_name",
                      "client_last_name"
                    ],
                    "properties": {
                      "currency": {
                        "type": "string",
                        "enum": [
                          "XOF"
                        ]
                      },
                      "merchant_transaction_id": {
                        "type": "string"
                      },
                      "amount": {
                        "type": "number"
                      },
                      "client_phone_number": {
                        "type": "string"
                      },
                      "payment_method": {
                        "type": "string",
                        "enum": [
                          "OM_BF"
                        ]
                      },
                      "otp_code": {
                        "type": "string",
                        "default": "1234"
                      },
                      "direct_pay": {
                        "type": "boolean",
                        "default": false
                      },
                      "designation": {
                        "type": "string"
                      },
                      "client_first_name": {
                        "type": "string"
                      },
                      "client_last_name": {
                        "type": "string"
                      }
                    }
                  },
                  {
                    "type": "object",
                    "required": [
                      "currency",
                      "merchant_transaction_id",
                      "amount",
                      "client_phone_number",
                      "client_email",
                      "payment_method",
                      "direct_pay",
                      "success_url",
                      "failed_url",
                      "notify_url"
                    ],
                    "properties": {
                      "currency": {
                        "type": "string",
                        "enum": [
                          "XOF"
                        ]
                      },
                      "merchant_transaction_id": {
                        "type": "string"
                      },
                      "amount": {
                        "type": "number"
                      },
                      "client_phone_number": {
                        "type": "string"
                      },
                      "payment_method": {
                        "type": "string",
                        "enum": [
                          "OM_BF",
                          "MOOV_BF"
                        ]
                      },
                      "otp_code": {
                        "type": "string",
                        "default": "1234"
                      },
                      "direct_pay": {
                        "type": "boolean",
                        "default": false
                      },
                      "designation": {
                        "type": "string"
                      },
                      "client_first_name": {
                        "type": "string"
                      },
                      "client_last_name": {
                        "type": "string"
                      },
                      "success_url": {
                        "type": "string"
                      },
                      "failed_url": {
                        "type": "string"
                      },
                      "notify_url": {
                        "type": "string"
                      }
                    }
                  }
                ]
              },
              "examples": {
                "MOOV BJ": {
                  "summary": "BJ - Payment with MOOV BJ",
                  "value": {
                    "currency": "XOF",
                    "merchant_transaction_id": "OM12345",
                    "amount": 100,
                    "success_url": "http://demo.paymetrust-test.net/notification",
                    "failed_url": "http://demo.paymetrust-test.net/notification/cancel/",
                    "notify_url": "http://demo.paymetrust-test.net/notification/notification",
                    "client_phone_number": "+2290707200200",
                    "client_email": "client@example.com",
                    "payment_method": "MOOV_BJ",
                    "direct_pay": false,
                    "designation": "Payment for order #1234",
                    "client_first_name": "John",
                    "client_last_name": "Doe"
                  }
                },
                "MTN BJ": {
                  "summary": "BJ - payment with MTN BJ",
                  "value": {
                    "currency": "XOF",
                    "merchant_transaction_id": "MTN12345",
                    "amount": 100,
                    "success_url": "http://demo.paymetrust-test.net/notification",
                    "failed_url": "http://demo.paymetrust-test.net/notification/cancel/",
                    "notify_url": "http://demo.paymetrust-test.net/notification/notification",
                    "client_phone_number": "+2260707200200",
                    "client_email": "client@example.com",
                    "payment_method": "MTN_BJ",
                    "direct_pay": false,
                    "designation": "Payment for order MTN#12345",
                    "client_first_name": "Jane",
                    "client_last_name": "Doe"
                  }
                },
                "OM BF": {
                  "summary": "BF - Payment with Orange BF",
                  "value": {
                    "currency": "XOF",
                    "merchant_transaction_id": "OM12345",
                    "amount": 100,
                    "success_url": "http://demo.paymetrust-test.net/notification",
                    "failed_url": "http://demo.paymetrust-test.net/notification/cancel/",
                    "notify_url": "http://demo.paymetrust-test.net/notification/notification",
                    "client_phone_number": "+2260707200200",
                    "payment_method": "OM_BF",
                    "otp_code": "1234",
                    "direct_pay": false,
                    "designation": "Payment for order #1234",
                    "client_first_name": "John",
                    "client_last_name": "Doe"
                  }
                },
                "MOOV BF": {
                  "summary": "BF - payment with MOOV BF",
                  "value": {
                    "currency": "XOF",
                    "merchant_transaction_id": "MOOV12345",
                    "amount": 100,
                    "success_url": "http://demo.paymetrust-test.net/notification",
                    "failed_url": "http://demo.paymetrust-test.net/notification/cancel/",
                    "notify_url": "http://demo.paymetrust-test.net/notification/notification",
                    "client_phone_number": "+2260707200200",
                    "client_email": "client@example.com",
                    "payment_method": "MOOV_BF",
                    "direct_pay": false,
                    "designation": "Payment for order #5678",
                    "client_first_name": "Jane",
                    "client_last_name": "Doe"
                  }
                },
                "OM CI": {
                  "summary": "CI - Payment with Orange CI",
                  "value": {
                    "currency": "XOF",
                    "merchant_transaction_id": "OM12345",
                    "amount": 100,
                    "success_url": "http://demo.paymetrust-test.net/notification",
                    "failed_url": "http://demo.paymetrust-test.net/notification/cancel/",
                    "notify_url": "http://demo.paymetrust-test.net/notification/notification",
                    "client_phone_number": "+2250707200200",
                    "payment_method": "OM_CI",
                    "otp_code": 1234,
                    "designation": "Payment for order #5678",
                    "client_first_name": "Jane",
                    "client_last_name": "Doe",
                    "direct_pay": false
                  }
                },
                "MTN CI": {
                  "summary": "CI - Payment with MTN CI",
                  "value": {
                    "currency": "XOF",
                    "merchant_transaction_id": "MTN12345",
                    "amount": 100,
                    "success_url": "http://demo.paymetrust-test.net/notification",
                    "failed_url": "http://demo.paymetrust-test.net/notification/cancel/",
                    "notify_url": "http://demo.paymetrust-test.net/notification/notification",
                    "client_phone_number": "+2250707200200",
                    "payment_method": "MTN_CI",
                    "otp_code": 1234,
                    "direct_pay": false
                  }
                },
                "MOOV CI": {
                  "summary": "CI - Payment with MOOV CI",
                  "value": {
                    "currency": "XOF",
                    "merchant_transaction_id": "MOOV12345",
                    "amount": 100,
                    "success_url": "http://demo.paymetrust-test.net/notification",
                    "failed_url": "http://demo.paymetrust-test.net/notification/cancel/",
                    "notify_url": "http://demo.paymetrust-test.net/notification/notification",
                    "client_phone_number": "+2250707200200",
                    "client_email": "client@example.com",
                    "payment_method": "MOOV_CI",
                    "direct_pay": false
                  }
                },
                "Wave CI": {
                  "summary": "CI - Payment with Wave CI",
                  "value": {
                    "currency": "XOF",
                    "merchant_transaction_id": "WAVE12345",
                    "amount": 200,
                    "success_url": "http://demo.paymetrust-test.net/notification",
                    "failed_url": "http://demo.paymetrust-test.net/notification/cancel/",
                    "notify_url": "http://demo.paymetrust-test.net/notification/notification",
                    "client_phone_number": "+2250707200200",
                    "client_name": "John Doe",
                    "payment_method": "WAVE_CI",
                    "direct_pay": false
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Payment processed successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "status": {
                      "type": "string"
                    },
                    "transaction_id": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "code": 200,
                    "status": "OK",
                    "transaction_id": "txn_123456"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid request parameters",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "status": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "code": 400,
                    "status": "ERROR",
                    "description": "Invalid request parameters."
                  }
                }
              }
            }
          }
        }
      }
    },
    "/payment/{payment_token}": {
      "get": {
        "summary": "Check Payment Status",
        "description": "Checks the status of a payment transaction using the transaction ID.",
        "tags": [
          "Payment"
        ],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "payment_token",
            "in": "path",
            "required": true,
            "description": "The ID of the transaction to check.",
            "schema": {
              "type": "string",
              "example": "e2244957e8eb4349853bd39b1539ba3a"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Payment status retrieved successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "status": {
                      "type": "string"
                    },
                    "transaction_id": {
                      "type": "string"
                    },
                    "payment_status": {
                      "type": "string"
                    },
                    "details": {
                      "type": "object"
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "status": "OK",
                  "transaction_id": "e2244957e8eb4349853bd39b1539ba3a",
                  "payment_status": "COMPLETED",
                  "details": {
                    "message": "Transaction successful."
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request - Invalid transaction ID",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "status": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "code": 400,
                  "status": "BAD_REQUEST",
                  "description": "Invalid transaction ID."
                }
              }
            }
          },
          "404": {
            "description": "Not Found - Transaction ID does not exist",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "status": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "status": "NOT_FOUND",
                  "description": "Transaction ID not found."
                }
              }
            }
          }
        }
      }
    },
    "/transfer": {
      "post": {
        "summary": "Process Transfer",
        "description": "Initiates a transfer request. This endpoint supports multiple configurations based on country requirements.\n- For **Benin (BJ)**: Use MOOV_BJ or  MTN_BJ.\n- For **Burkina Faso (BF)**: Use OM_BF, MOOV_BF or WAVE_BF for payment_method.\n- For **CÃ´te d'Ivoire (CI)**: Use OM_CI, MOOV_CI, WAVE_CI or MTN_CI for payment_method.\n- For **Mali (ML)**: Use OM_ML or MOOV_ML.\n- For **Cameroon (CM)**: Use OM_CM or MTN_CM.\n- For **Guinea (GN)**: Use OM_GN or MTN_GN.\n- For **Senegal (SN)**: Use OM_SN, WAVE_SN, FREE_SN or EXPRESSO.\n- For **Togo (TG)**: Use MOOV_TG or TMONEY_TG.\n- For **Niger (NE)**: Use AIRTEL_NE.\n- For **RDC (CD)**: Use OM_CD, AIRTEL_CD, MPESA_CD or AFRICELL_CD.\n",
        "tags": [
          "Transfert"
        ],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "oneOf": [
                  {
                    "type": "object",
                    "required": [
                      "currency",
                      "merchant_transaction_id",
                      "amount",
                      "client_phone_number",
                      "payment_method",
                      "reason"
                    ],
                    "properties": {
                      "currency": {
                        "type": "string",
                        "enum": [
                          "XOF"
                        ]
                      },
                      "merchant_transaction_id": {
                        "type": "string"
                      },
                      "amount": {
                        "type": "number"
                      },
                      "client_phone_number": {
                        "type": "string"
                      },
                      "payment_method": {
                        "type": "string",
                        "enum": [
                          "OM_BF",
                          "MOOV_BF"
                        ]
                      },
                      "reason": {
                        "type": "string"
                      }
                    }
                  },
                  {
                    "type": "object",
                    "required": [
                      "currency",
                      "merchant_transaction_id",
                      "amount",
                      "client_phone_number",
                      "client_email",
                      "payment_method",
                      "reason"
                    ],
                    "properties": {
                      "currency": {
                        "type": "string",
                        "enum": [
                          "XOF"
                        ]
                      },
                      "merchant_transaction_id": {
                        "type": "string"
                      },
                      "amount": {
                        "type": "number"
                      },
                      "client_phone_number": {
                        "type": "string"
                      },
                      "payment_method": {
                        "type": "string",
                        "enum": [
                          "MOOV_BF"
                        ]
                      },
                      "reason": {
                        "type": "string"
                      },
                      "client_email": {
                        "type": "string"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Transfer Request Successfully Processed",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "enum": [
                        "success"
                      ]
                    },
                    "transaction_id": {
                      "type": "string",
                      "description": "The transaction ID generated for the transfer."
                    },
                    "message": {
                      "type": "string",
                      "description": "A success message confirming the transaction."
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request - Invalid Input Data",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "enum": [
                        "failure"
                      ]
                    },
                    "error_code": {
                      "type": "string"
                    },
                    "error_message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid API Key or Token",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "enum": [
                        "failure"
                      ]
                    },
                    "error_message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error - Unexpected Issue",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "enum": [
                        "failure"
                      ]
                    },
                    "error_message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/transfer/{transaction_id}": {
      "get": {
        "summary": "Check Transfer Status",
        "description": "Checks the status of a transfer based on the provided transaction ID.\n",
        "tags": [
          "Transfert"
        ],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "transaction_id",
            "in": "path",
            "required": true,
            "description": "The transaction ID of the transfer to check.",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Status of the Transfer",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "example": 100
                    },
                    "status": {
                      "type": "string",
                      "enum": [
                        "SUCCESS",
                        "PENDING",
                        "FAILED"
                      ]
                    },
                    "merchant_transaction_id": {
                      "type": "string",
                      "description": "Merchant's transaction ID.",
                      "example": "154MM584KKKK766OO10PPKPOO"
                    },
                    "transaction_id": {
                      "type": "string",
                      "description": "The unique ID of the transfer transaction.",
                      "example": "e21ff257-3b97-4360-9d6d-a232a77081fa"
                    },
                    "amount": {
                      "type": "string",
                      "description": "The amount involved in the transaction.",
                      "example": "200"
                    },
                    "fee_amount": {
                      "type": "string",
                      "description": "The fee applied to the transaction.",
                      "example": "0"
                    },
                    "phone_number": {
                      "type": "string",
                      "description": "The client's phone number for the transfer.",
                      "example": "+2210707200200"
                    },
                    "currency": {
                      "type": "string",
                      "description": "The currency used for the transaction.",
                      "example": "XOF"
                    },
                    "user": {
                      "type": "string",
                      "nullable": true,
                      "description": "Information about the user, if available."
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request - Invalid Transaction ID",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "example": 400
                    },
                    "status": {
                      "type": "string",
                      "enum": [
                        "BAD_REQUEST"
                      ]
                    },
                    "description": {
                      "type": "string",
                      "description": "Error details about the bad request.",
                      "example": "Invalid transaction ID."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found - Transaction ID Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "example": 404
                    },
                    "status": {
                      "type": "string",
                      "enum": [
                        "NOT_FOUND"
                      ]
                    },
                    "description": {
                      "type": "string",
                      "description": "Message indicating that the transaction ID was not found.",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error - Unexpected Issue",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "enum": [
                        "failure"
                      ]
                    },
                    "error_message": {
                      "type": "string",
                      "description": "A message describing the server error."
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}